[package]
name = "ltseq_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "ltseq_core"
crate-type = ["cdylib"]

[dependencies]
# Python co-op
pyo3 = { version = "0.27.2", features = ["extension-module", "macros"] }

datafusion = "52.1.0"

# async executor utilities
futures-util = "0.3"

tokio = { version = "1.49", features = ["rt", "rt-multi-thread"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = "symbols"
